[package]
name = "bench"
version = "0.1.0"
authors = ["Ian Page Hands <iphands@gmail.com>"]
edition = "2018"
publish = false

[[bench]]
name = "proc"
harness = false

[["bench"]]
name = "macro"
harness = false

[["bench"]]
name = "direntry"
harness = false

[dev-dependencies]
criterion = "0.3"
