---
settings:
  # color_bar:   "#fff"
  # color_background: "rgba(0, 0, 0, 0.75);"
  # color_label: "#eee"
  # color_text:  "#fff"
  # base_opacity:  "0.8"
  # decoration: false
  # font_size: large
  # mod_top: 2
  # mod_fs: 5
  # resizable: false
  # skip_taskbar: true
  timeout: 1
  # xpos: 3380
  # ypos: 0

ui:
  - text: SYSTEM
    type: system
    items:
      - func: hostname
        text: "Hostname:"

      - func: kernel
        text: "Kernel:"

      - func: uptime
        text: "Uptime:"

      - func: cpu_usage
        text: "CPU usage:"
        widget: bar

      - func: cpu_temp_sys
        text: "CPU temp:"

      - func: ram_usage
        text: "RAM usage:"
        widget: bar

      - func: procs_count
        text: "Running processes:"

      - func: load
        text: "Load:"

      # - func: gpu_temp
      #   text: "GPU Temp:"

  - text: CPUS
    type: cpus
    func: cpus
    text: "CPU"

  - text: TOP CPU
    type: cpu_consumers
    limit: 5

  - text: TOP MEMORY
    type: mem_consumers
    limit: 5

  - text: FILESYSTEM
    type: filesystem
    items:
      - text: "root:"
        mount_point: /
