---
settings:
  background_color: "#656565"
  debug: false
  decoration: false
  font-size: medium
  resizable: false
  skip_taskbar: true
  timeout: 2
  xpos: 3450
  ypos: 5

ui:
  - text: SYSTEM
    items:
      - func: hostname
        text: "Hostname:"

      - func: kernel
        text: "Kernel:"

      - func: uptime
        text: "Uptime:"

      - func: cpu_usage
        text: "CPU usage:"
        widget: bar

      - func: sensor_info
        sensor_name: k10temp-pci-00c3
        label_name: Tdie
        val: "{}C"
        text: "CPU temp:"
        whole: true

      - func: sensor_info
        sensor_name: k10temp-pci-00c3
        label_name: Vcore
        val: "{}mV"
        text: "CPU vcore:"
        whole: false

      - func: nvidia_gpu_temp
        text: "GPU Temp:"

      - func: ram_usage
        text: "RAM usage:"
        widget: bar

      - func: procs
        text: "Running processes:"

      - func: load
        text: "Load:"

      # - func: cpu_temp_sys
      #   text: "CPU Temp:"

  - text: CPUS
    items:
      - type: cpus
        func: cpus
        text: "CPU"

# - text: FILESYSTEM
#   items:
# - text: NETWORKING
#   items:
