---
settings:
  # color_bar:   "#fff"
  # color_label: "#eee"
  # color_text:  "#fff"
  # decoration: false
  # resizable: false
  # skip_taskbar: true

  color_background: "#656565"
  color_bar:      "#e1eeff"
  color_bar_med:  "#ffeeaa"
  color_bar_high: "#ffaaaa"

  color_label: "#87d7ff"
  color_text:  "#e1eeeb"

  font_family: "\"Droid Sans Mono\""
  # font_family: "\"Noto Sans Mono ExtraCondensed Medium\""
  font_size: medium
  timeout: 1
  xpos: 3340
  ypos: 0
  mod_top: 2
  mod_fs:  5

ui:
  - text: SYSTEM
    type: system
    items:
      - func: hostname
        text: "Hostname:"

      - func: kernel
        text: "Kernel:"

      - func: uptime
        text: "Uptime:"

      - func: cpu_usage
        text: "CPU usage:"
        widget: bar

      - func: sensor_info
        sensor_name: k10temp-pci-00c3
        label_name: Tdie
        val: "{}C"
        text: "CPU temp:"
        whole: true

      - func: sensor_info
        sensor_name: k10temp-pci-00c3
        label_name: Vcore
        val: "{}mV"
        text: "CPU vcore:"
        whole: false

      - func: nvidia_gpu_temp
        text: "GPU Temp:"

      - func: ram_usage
        text: "RAM usage:"
        widget: bar

      - func: procs_count
        text: "Running processes:"

      - func: load
        text: "Load:"

  - text: CPUS
    type: cpus
    func: cpus
    text: "CPU"

  - text: TOP CPU
    type: cpu_consumers
    limit: 5

  - text: TOP MEMORY
    type: mem_consumers
    limit: 5

  - text: FILESYSTEM
    type: filesystem
    items:
      - text: "boot:"
        mount_point: /boot
      - text: "root:"
        mount_point: /
      - text: "noir:"
        mount_point: /mnt/noir/scratch
