---
settings:
  # color_background: "rgba(255, 255, 255, 0.25);"
  # color_bar:   "#fff"
  # color_label: "#87d7ff"
  # color_text:  "#fff"

  # decoration: true
  # resizable: true
  # skip_taskbar: false

  bar_height: 8px

  # color_background: "#656565"
  color_background: "#000000"
  color_bar:      "#e1eeff"
  color_bar_med:  "#ffeeaa"
  color_bar_high: "#ffaaaa"

  color_label: "#87d7ff"
  color_text:  "#e1eeeb"

  # decoration: false
  # resizable: false
  # skip_taskbar: true
  # color_background: "#262626"
  #font_family: "\"Noto Sans\""
  font_family: "\"Anadale Mono Regular\""
  font_size: 11pt
  timeout: 1
  mod_top: 2
  xpos: 2185
  ypos: 0

ui:
  - text: SYSTEM
    type: system
    items:
      - func: hostname
        text: "Hostname:"

      - func: kernel
        text: "Kernel:"

      - func: uptime
        text: "Uptime:"

      - func: sensor_info
        sensor_name: thinkpad-isa-0000
        label_name: fan1
        val: "{} RPM"
        text: "Fan speed:"
        whole: true

      # - func: sensor_info
      #   sensor_name: pch_skylake-virtual-0
      #   label_name: temp1
      #   val: "{} C"
      #   text: "CPU temp:"
      #   whole: true

      - func: cpu_usage
        text: "CPU usage:"
        widget: bar

      - func: cpu_temp_sys
        text: "CPU temp:"

      - func: ram_usage
        text: "RAM usage:"
        widget: bar

      - func: procs_count
        text: "Running processes:"

      - func: load
        text: "Load:"

  - text: BATTERY
    type: battery
    items:
      - name: bat0
        path: /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1b/PNP0C09:00/PNP0C0A:00/power_supply/BAT0
        battery_text:  "Unplugged  ðŸ”‹"
        pluggged_text: "Plugged in âš¡"
        percent_template: "{}%"

  - text: CPU
    type: cpus
    func: cpus
    split: true

  - text: TOP CPU
    type: cpu_consumers
    limit: 5

  - text: TOP MEMORY
    type: mem_consumers
    limit: 5

  - text: NETWORKING
    type: net
    items:
      - name: wifi
        interface: wlp0s20f3

  - text: FILESYSTEM
    type: filesystem
    items:
      - text: "root:"
        mount_point: /
