---
settings:
  background_color: "#000"
  debug: false
  decoration: false
  font-size: large
  resizable: false
  timeout: 1
  xpos: 1540
  ypos: 20

ui:
  - text: SYSTEM
    items:
      - func: hostname
        text: "Hostname:"

      - func: kernel
        text: "Kernel:"

      - func: uptime
        text: "Uptime:"

      - func: cpu_usage
        text: "CPU usage:"
        widget: bar

      - func: cpu_temp_sys
        text: "CPU temp:"

      - func: ram_usage
        text: "RAM usage:"
        widget: bar

      - func: procs
        text: "Running processes:"

      - func: load
        text: "Load:"

      # - func: gpu_temp
      #   text: "GPU Temp:"

  - text: CPUS
    type: cpus
    func: cpus
    text: "CPU"

  - text: TOP CPU
    type: cpu_consumers
    limit: 5

  - text: TOP MEMORY
    type: mem_consumers
    limit: 5

# - text: FILESYSTEM
#   items:
# - text: NETWORKING
#   items:
